name: attendencemeter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sembast: ^2.2.0+1
  path_provider: ^1.6.5
  built_collection: ^4.3.2
  unicorndial: ^1.1.5
  datetime_picker_formfield: ^1.0.0
  intl: ^0.16.1
  charts_flutter: ^0.9.0
  pdf: ^1.5.0
  flutter_full_pdf_viewer: ^1.0.6
  path: ^1.6.4
  # simple_permissions: ^0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/addcrcstdnt1.png
    - images/studentedit.png
    - images/prvsstdnt.png
    - images/importcrc.png
    - images/course.png
    - images/courseadd.png
    - images/student.png
    - images/stdntprf.png
    - images/studentedit.png
    - images/stat.png
    - images/statstud.png
    - images/statgraph.png
    - images/attndnc.png
    - images/attndnce.png
    - images/attndncprrt.png
    - images/attndncpart1.png
    - images/attndncsheet.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProximaNova
      fonts:
        - asset: fonts/Proxima-Nova-Alt-Bold.otf
        - asset: fonts/Proxima-Nova-Alt-Light.otf
        - asset: fonts/Proxima-Nova-Alt-Thin.otf
        - asset: fonts/Proxima-Nova-Black.otf
        - asset: fonts/Proxima-Nova-Bold.otf
        - asset: fonts/Proxima-Nova-Extrabold.otf
        - asset: fonts/Proxima-Nova-Thin.otf
        - asset: fonts/ProximaNova-Regular.otf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
